const randomName = [
  "Bolt",
  "Hunter",
  "Alpha",
  "Wolf",
  "Spike",
  "Rhino",
  "Saber",
  "Titus",
  "Blaze",
  "Ripley",
  "Chess",
  "Maze",
  "Ace",
  "Flare",
  "Quiz",
  "Tricks",
  "Harley",
  "Rex",
  "Bandit",
  "Enigma",
  "Raven",
  "Storm",
  "Ripper",
  "Archer",
  "Cobra",
  "Gunner",
  "Valley",
  "Tango",
  "Shadow",
  "Juno",
  "Flame",
  "Apollo",
  "Thunder",
  "Quartz",
  "Mocha",
  "Pistol",
  "Frisk",
  "Rider",
  "Copper",
  "Pip",
  "Ice",
  "Dirt",
  "Solo",
  "River",
  "Vice",
  "Shot",
  "Stinger",
  "Kong",
  "Red",
  "Shank"
]
const randomBreed = [
  "affenpinscher",
  "Afghan hound",
  "Airedale terrier",
  "beagle",
  "bulldog",
  "bullmastiff",
  "cairn terrier",
  "Canaan dog",
  "Chesapeake Bay retriever",
  "Chihuahua",
  "chow chow",
  "collie",
  "Dalmatian",
  "flat-coated retriever",
  "fox terrier",
  "foxhound",
  "French bulldog",
  "German shepherd",
  "German shorthaired pointer",
  "German wirehaired pointer",
  "golden retriever",
  "Gordon setter",
  "Great Dane",
  "greyhound",
  "Irish setter",
  "Irish water spaniel",
  "Irish wolfhound",
  "Jack Russell terrier",
  "Maltese",
  "Manchester terrier",
  "mastiff",
  "Mexican hairless",
  "Newfoundland",
  "Norwegian elkhound",
  "Norwich terrier",
  "otterhound",
  "papillon",
  "Pekingese",
  "pointer",
  "Pomeranian",
  "poodle",
  "pug",
  "puli",
  "Rhodesian ridgeback",
  "Rottweiler",
  "Saint Bernard",
  "saluki",
  "Samoyed",
  "schipperke",
  "schnauzer",
  "Scottish deerhound",
  "Scottish terrier",
  "Sealyham terrier",
  "Shetland sheepdog",
  "shih tzu",
  "Siberian husky",
  "Skye terrier",
  "Staffordshire bull terrier",
  "soft-coated wheaten terrier",
  "Sussex spaniel",
  "spitz",
  "Tibetan terrier",
  "vizsla",
  "Weimaraner",
  "Welsh terrier",
  "West Highland white terrier",
  "whippet",
  "Yorkshire terrier"
]
const randomDog = () => {
  const name = randomName[Math.floor(Math.random() * randomName.length)];
  const age = Math.ceil(Math.random() * 16);
  const breed = randomBreed[Math.floor(Math.random() * randomBreed.length)];
  const newDog = {
    name: name,
    age: age,
    breed: breed
  };
  return newDog;
};

module.exports = {
  randomDog
}